# Project: AED2_Project
# Makefile created by Dev-C++ 5.9.2

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = main.o
LINKOBJ  = main.o
LIBS     = -L"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/lib" -L"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -g3
INCS     = -I"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/include" -I"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include"
CXXINCS  = -I"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/include" -I"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include" -I"C:/Users/fabio/OneDrive/Ambiente de Trabalho/Tudo/pen -primavera/IPCA/LP/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.8.1/include/c++"
BIN      = AED2_Project.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
